### ISSUE TITLE
[traceback] cryptography.exceptions.UnsupportedAlgorithm: Backend object does not implement PBKDF2HMACBackend in Python 3.6

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#219]
/cc @davehunt 

Just noticed this on https://travis-ci.org/mozilla/fxapom/jobs/353970801:

**```cryptography.exceptions.UnsupportedAlgorithm: Backend object does not implement PBKDF2HMACBackend```**

```
[gw0] [100%] PASSED tests/test_fxa_test_account.py::TestFxATestAccount::test_create_new_account[https://stable.dev.lcip.org/auth/] Exception ignored in: <bound method FxATestAccount.__del__ of <fxapom.fxapom.FxATestAccount object at 0x7fac9e55a0f0>>
Traceback (most recent call last):
  File "/src/fxapom/fxapom.py", line 66, in __del__
  File "/src/.tox/py36/lib/python3.6/site-packages/fxa/core.py", line 113, in destroy_account
  File "/src/.tox/py36/lib/python3.6/site-packages/fxa/core.py", line 104, in _get_stretched_password
  File "/src/.tox/py36/lib/python3.6/site-packages/fxa/crypto.py", line 58, in quick_stretch_password
  File "/src/.tox/py36/lib/python3.6/site-packages/cryptography/hazmat/primitives/kdf/pbkdf2.py", line 22, in __init__
cryptography.exceptions.UnsupportedAlgorithm: Backend object does not implement PBKDF2HMACBackend.
```

**Comment by stephendonner** [comment]
Probably; I haven't seen this since, either, I don't think.  Maybe a fluke/blip on either Travis or FxA side(s).

**Comment by stephendonner** [comment]
....and it's back: https://travis-ci.org/mozilla/fxapom/jobs/356282078

**Comment by stephendonner** [comment]
[fxapom-travisci-log.txt](https://github.com/mozilla/fxapom/files/1835014/fxapom-travisci-log.txt)

**Comment by davehunt** [comment]
Did you retrigger the job again? It looks like this is an ignored exception from https://github.com/mozilla/PyFxA/blob/c4a70fa318c86ab4721a6e2d20318b139bbb3b2a/fxa/crypto.py#L53-L59 and is probably only shown when a test fails, but happens every time. Perhaps @rfk could confirm if this is something we need to look into.
